objects/ConnectedAppCredentialsSandbox__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CallbackUrl__c</fullName>
        <label>CallbackUrl</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret__c</fullName>
        <label>Secret</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>ConnectedAppCredentialsSandbox</label>
</CustomObject>

objects/Sandbox__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain_URL__c</fullName>
        <label>Domain URL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sandbox_Info_Id__c</fullName>
        <label>Sandbox Info Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <label>Sandbox</label>
    <nameField>
        <label>Sandbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sandboxes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SandboxId__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>SandboxId</label>
</CustomObject>

globalValueSets/Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Activating</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Deleted</fullName>
    </customValue>
    <customValue>
        <fullName>Deleting</fullName>
    </customValue>
    <customValue>
        <fullName>Discarding</fullName>
    </customValue>
    <customValue>
        <fullName>Locked</fullName>
    </customValue>
    <customValue>
        <fullName>Locking</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Activation</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Sampling</fullName>
    </customValue>
    <customValue>
        <fullName>Stopped</fullName>
    </customValue>
    <customValue>
        <fullName>Suspended</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

classes/SandboxTestDataFactory.cls
public class SandboxTestDataFactory {
   public static Sandbox__c createOrg(){
        Sandbox__c org = New Sandbox__c();
        org.Name = 'TestOrg123';
        org.Sandbox_Info_Id__c = '87jhktnffilh8';
        org.Access_Token__c = '8764ynfafif9r3rny23099hiknefprfu920r';
        org.Domain_URL__c='https://cloudfulcrum.copadodev.com';
        org.Status__c = 'Completed';
        insert org;
        return org;
    }
    
    public static void createCredsCustomSetting(){
       //createOrg();
        ConnectedAppCredentialsSandbox__c creds = ConnectedAppCredentialsSandbox__c.getInstance();
        creds.Key__c = 'iuhddiuayd98doqwhd98xsidpsd';
        creds.Secret__c = 'dwdu8wd8hopwndi9w8yd9a8sndoasyud';
        creds.CallbackUrl__c = 'https://cloudfulcrum.copadodev.com';
        upsert creds;
    }
    
    public static void createCustomSetting(){
       createOrg();
        Sandbox__c org = [Select Id,Name,Sandbox_Info_Id__c from Sandbox__c Where Name = 'TestOrg123' Limit 1];
        SandboxId__c orgId = SandboxId__c.getInstance();
        orgId.Id__c = org.Id;
        upsert orgId;
    }
}