objects/ConnectedAppCredentialsSandbox__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CallbackUrl__c</fullName>
        <label>CallbackUrl</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret__c</fullName>
        <label>Secret</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>ConnectedAppCredentialsSandbox</label>
</CustomObject>

objects/Sandbox__c.object
<CustomObject>
    <fields>
        <fullName>Domain_URL__c</fullName>
        <label>Domain URL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sandbox</label>
    <nameField>
        <label>Sandbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sandboxes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SandboxId__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>SandboxId</label>
</CustomObject>

classes/AuthorizationCodeFlowSandbox.cls
public with sharing class AuthorizationCodeFlowSandbox {
    @AuraEnabled
    public static String auth(Id orgId){
        system.debug('orgId==='+orgId);
        ConnectedAppCredentialsSandbox__c creds = ConnectedAppCredentialsSandbox__c.getInstance();
        System.debug(creds.Key__c);
        System.debug(creds.Secret__c);
        Sandbox__c org = [Select Id, Name, Domain_Url__c from Sandbox__c where Id =: orgId];
        Http http = New Http();
        HttpRequest req = New HttpRequest();
        req.setEndpoint(org.Domain_URL__c+'/services/oauth2/authorize?response_type=code&client_id='+creds.Key__c+'&redirect_uri='+creds.CallbackUrl__c);
        req.setHeader('Content-Type','application/x-www-form-urlencoded');
        req.setMethod('POST');
        HttpResponse res = http.send(req);
        System.debug(res.getHeader('Location'));
        String redirectUrl = res.getHeader('Location');
        //PageReference pageRef = new PageReference(redirectUrl);
        //String redirectUrl1 = pageRef.getUrl();
        //pageRef.setRedirect(true);
        System.debug(redirectUrl);
        SandboxId__c idOrg = SandboxId__c.getInstance();
        idOrg.Id__c = org.Id;
        upsert idOrg;
        //storeValueInCache(org.Id);
        return redirectUrl;
    }
}