objects/ProdCred__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>DomainURL__c</fullName>
        <label>DomainURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>clientid__c</fullName>
        <label>clientid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>clientsecret__c</fullName>
        <label>clientsecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Prod Credential for Sandbox Refresh</label>
</CustomObject>

objects/Sandbox__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Refresh_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Refresh By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sandboxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Refresh__c</fullName>
        <label>Last Refresh</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LicenseType__c</fullName>
        <label>LicenseType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LicenseType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Poll_Time__c</fullName>
        <label>Poll Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sandbox_Info_Id__c</fullName>
        <label>Sandbox Info Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org</label>
        <referenceTo>Sandbox__c</referenceTo>
        <relationshipLabel>Sandboxes</relationshipLabel>
        <relationshipName>Sandboxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <label>Sandbox</label>
    <nameField>
        <label>Sandbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sandboxes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/LicenseType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DEVELOPER</fullName>
    </customValue>
    <customValue>
        <fullName>DEVELOPER_PRO</fullName>
    </customValue>
    <customValue>
        <fullName>PARTIAL</fullName>
    </customValue>
    <customValue>
        <fullName>FULL</fullName>
    </customValue>
    <masterLabel>LicenseType</masterLabel>
</GlobalValueSet>

globalValueSets/Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Activating</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Deleted</fullName>
    </customValue>
    <customValue>
        <fullName>Deleting</fullName>
    </customValue>
    <customValue>
        <fullName>Discarding</fullName>
    </customValue>
    <customValue>
        <fullName>Locked</fullName>
    </customValue>
    <customValue>
        <fullName>Locking</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Activation</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Sampling</fullName>
    </customValue>
    <customValue>
        <fullName>Stopped</fullName>
    </customValue>
    <customValue>
        <fullName>Suspended</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

classes/SandboxRefreshTest.cls
@isTest
public class SandboxRefreshTest {
    @testsetup
    public static void testSet(){
        sandbox__c sbxtest = new Sandbox__c();
        sbxtest.name = 'QATest';
        sbxtest.Sandbox_Info_Id__c ='1234567890';
        sbxtest.Access_Token__c = '01234567';
        sbxtest.LicenseType__c ='DEVELOPER';
        insert sbxtest;

        sandbox__c sbxtest1 = new Sandbox__c();
        sbxtest1.name = 'DevTest';
        sbxtest1.Sandbox_Info_Id__c ='9876543210';
        sbxtest1.LicenseType__c ='DEVELOPER';
        sbxtest1.Access_Token__c = '01234567';
        sbxtest1.Source_Org__c=sbxtest.id;
        insert sbxtest1;

        ProdCred__c pcd = new ProdCred__c();
        pcd.clientid__c ='1234567890';
        pcd.clientsecret__c ='9876543210';
        pcd.domainurl__c = 'https://localhost';
        insert pcd;

    }

    @isTest
    static void testMethod1(){
        sandbox__c sbxdev = [select id,name,Source_Org__c,Sandbox_Info_Id__c,source_org__r.Sandbox_Info_Id__c,LicenseType__c,Last_Refresh__c,Last_Refresh_By__c,Status__c from Sandbox__c where name='DevTest'];
        Test.setMock(HttpCalloutMock.class,new SandboxRefreshMock());
        String str = SandboxRefresh.refreshSandbox(sbxdev.id);
        Assert.isNotNull(str);
    }
    
    @isTest
    static void testMethod2(){
        sandbox__c sbxdev = [select id,name,Source_Org__c,Sandbox_Info_Id__c,source_org__r.Sandbox_Info_Id__c,LicenseType__c,Last_Refresh__c,Last_Refresh_By__c,Status__c from Sandbox__c where name='DevTest'];
        Test.setMock(HttpCalloutMock.class,new SandboxRefreshMock());
        String str = SandboxRefresh.getSandboxStatus(sbxdev.id);
        Assert.isNotNull(str);
    }
    
    @isTest
    static void testMethod3(){
        sandbox__c sbxdev = [select id,name,Source_Org__c,Sandbox_Info_Id__c,source_org__r.Sandbox_Info_Id__c,LicenseType__c,Last_Refresh__c,Last_Refresh_By__c,Status__c from Sandbox__c where name='DevTest'];
        Test.setMock(HttpCalloutMock.class,new SandboxRefreshMock());
        String str = SandboxRefresh.getAccessToken();
        Assert.isNotNull(str);
        
    }
    @isTest
    static void testMethod4(){
        sandbox__c sbxdev = [select id,name,Source_Org__c,Sandbox_Info_Id__c,source_org__r.Sandbox_Info_Id__c,LicenseType__c,Last_Refresh__c,Last_Refresh_By__c,Status__c from Sandbox__c where name='DevTest'];
        Test.setMock(HttpCalloutMock.class,new SandboxRefreshMock());
        List<Sandbox__c> sandboxList = New List<Sandbox__c>{sbxdev};
        SandboxRefresh.getSandboxStatusInvoke(sandboxList);
        sbxdev = [select id,name,Source_Org__c,Sandbox_Info_Id__c,source_org__r.Sandbox_Info_Id__c,Poll_Time__c,LicenseType__c,Last_Refresh__c,Last_Refresh_By__c,Status__c from Sandbox__c where name='DevTest'];
   		Assert.isNotNull(sbxdev.Poll_Time__c);	
    }

}