objects/Sandbox__c.object
<CustomObject>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Sandbox</label>
    <nameField>
        <label>Sandbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sandboxes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CallbackControllerSandboxTest.cls
@isTest
public class CallbackControllerSandboxTest {
@isTest
    static void testVFPageCallback(){
        String testCode = 'testCode';
        CallbackControllerSandbox.code = testCode;
        SandboxTestDataFactory.createOrg();
        SandboxTestDataFactory.createCustomSetting();
        SandboxTestDataFactory.createCredsCustomSetting();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class,new CallbackControllerMockSandbox());
        CallbackControllerSandbox.captureCode();
        Sandbox__c org = [Select Id, Name,Refresh_Token__c from Sandbox__c where Name =: 'TestOrg123' Limit 1];
        Assert.areEqual(org.Refresh_Token__c, 'abcdefghijklmnopqrstuvwxyz');
        Test.stopTest();
    }
}