objects/Sandbox__c.object
<CustomObject>
    <fields>
        <fullName>LicenseType__c</fullName>
        <label>LicenseType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LicenseType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sandbox_Info_Id__c</fullName>
        <label>Sandbox Info Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sandbox</label>
    <nameField>
        <label>Sandbox Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sandboxes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/LicenseType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DEVELOPER</fullName>
    </customValue>
    <customValue>
        <fullName>DEVELOPER_PRO</fullName>
    </customValue>
    <customValue>
        <fullName>PARTIAL</fullName>
    </customValue>
    <customValue>
        <fullName>FULL</fullName>
    </customValue>
    <masterLabel>LicenseType</masterLabel>
</GlobalValueSet>

classes/SandboxRefreshController.cls
public with sharing class SandboxRefreshController {
    @AuraEnabled
    public static List<Sandbox__c> getSandbox(string licenseType){
        system.debug(licenseType);
        return [SELECT Id, Name,Sandbox_Info_Id__c,LicenseType__c FROM Sandbox__c WHERE LicenseType__c = :licenseType];
    }

    @AuraEnabled(cacheable=true)
    public static List<Sandbox__c> getSandboxName(){
        return [SELECT Id, Name,Sandbox_Info_Id__c,LicenseType__c FROM Sandbox__c];
    }
}